cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update_cart/<int:cart_item_id>/', views.update_cart, name='update_cart'),
    path('delete_from_cart/<int:cart_item_id>/', views.delete_from_cart, name='delete_from_cart'),
]

myecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter

from product.views import home_view, ProductDetailView, ProductReviewViewSet

router = DefaultRouter()
router.register(r'reviews', ProductReviewViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('accounts/', include('accounts.urls')),
    path('products/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
path('create/', views.create_order, name='create_order'),
path('confirm/<int:order_id>/', views.confirm_order, name='confirm_order'),
path('awaiting_payment/<int:order_id>/', views.awaiting_payment, name='awaiting_payment'),
path('pay/<int:order_id>/', views.pay_order, name='pay_order'),
path('<int:order_id>/', views.order_detail, name='order_detail'),
path('<int:order_id>/cancel/', views.cancel_order, name='cancel_order'),
path('', views.order_history, name='order_history'),
path('thank_you/<int:order_id>',views.thank_you,name='thank_you'),
]

product/urls.py
from django.urls import path
from . import views
app_name = 'product'

urlpatterns = [
    path('', views.product_list_view, name='product_list'),
    path('detail/<int:pk>/', views.product_detail, name='product_detail'),
    path('detail/<int:pk>/submit_review/', views.product_review_submit, name='product_review_submit'),
    path('form',views.product_create_view,name='product_form'),
    path('category/skincare/', views.skincare_products, name='skincare_products'),
    path('category/makeup/', views.makeup_products, name='makeup_products'),
    path('category/haircare/', views.haircare_products, name='haircare_products'),
    path('out_of_stock/', views.out_of_stock, name='out_of_stock'),
]

cart/models.py
from django.db import models
from django.conf import settings
from product.models import Product  # assuming this is where your Product model is defined

class Cart(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    session_key = models.CharField(max_length=255, null=True, blank=True)  

    def __str__(self):
        return f"Cart of {self.user.username if self.user else 'Anonymous'}"

    @property
    def total_price(self):
        return sum(item.subtotal for item in self.items.all())

    @property
    def total_items(self):
        return sum(item.quantity for item in self.items.all())

    def remove_item(self, product_id):
        try:
            cart_item = self.items.get(product_id=product_id)
            cart_item.delete()
            return True  # Successfully removed
        except CartItem.DoesNotExist:
            return False  # Product not found in cart

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.product.name}"

    @property
    def subtotal(self):
        return self.product.price * self.quantity

cart/forms.py
from django import forms
from.models import CartItem
class CartItemForm(forms.ModelForm):
    class Meta:
        model = CartItem
        fields = ['quantity']

    def __init__(self, *args, **kwargs):
        super(CartItemForm, self).__init__(*args, **kwargs)
        self.fields['quantity'].widget.attrs.update({'class': 'form-control'})

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Cart, CartItem
from product.models import Product
from django import forms
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages

def get_or_create_cart(request):
    if request.user.is_authenticated:
        cart, _ = Cart.objects.get_or_create(user=request.user)
    else:
        session_key = request.session.session_key
        if not session_key:
            request.session.create()
            session_key = request.session.session_key
        cart, _ = Cart.objects.get_or_create(session_key=session_key)
    return cart
    
def cart_detail(request):
    cart = get_or_create_cart(request)  # Используем функцию для получения или создания корзины
    cart_items = cart.items.all()
    total_price = sum(item.product.price * item.quantity for item in cart_items)  # Вычисляем общую стоимость

    return render(request, 'cart/detail.html', {
        'cart_items': cart_items,
        'total_price': total_price
    })
def add_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart = get_or_create_cart(request)
    cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)
    if not created:
        cart_item.quantity += 1
    else:
        cart_item.quantity = 1
    cart_item.save()
    return redirect('cart:cart_detail')

class CartItemForm(forms.Form):
    quantity = forms.IntegerField(min_value=0)  # Устанавливаем минимальное значение

def update_cart(request, cart_item_id):
    cart_item = get_object_or_404(CartItem, id=cart_item_id)
    if request.method == 'POST':
        form = CartItemForm(request.POST)
        if form.is_valid():
            quantity = form.cleaned_data['quantity']
            if quantity > 0:
                cart_item.quantity = quantity
                cart_item.save()
                messages.success(request, "Количество товара успешно обновлено.")
            else:
                cart_item.delete()
                messages.success(request, "Товар удален из корзины.")
            return redirect('cart:cart_detail')
        else:
            messages.error(request, "Введено некорректное количество.")
    else:
        form = CartItemForm(initial={'quantity': cart_item.quantity})

    return render(request, 'cart/update_cart.html', {'cart_item': cart_item, 'form': form})
def delete_from_cart(request, cart_item_id):
    cart_item = get_object_or_404(CartItem, id=cart_item_id)
    cart_item.delete()
    return redirect('cart:cart_detail')

templates/cart/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
      <div class="col-md-6">
          <div class="card shadow">
              <div class="card-body">
                  <h1 class="card-title">Ваша корзина</h1>
                  {% if cart_items %}
                      {% for cart_item in cart_items %}
                          <p>{{ cart_item.product.name }} - {{ cart_item.quantity }} x {{ cart_item.product.price }} = {{ cart_item.subtotal }}</p>
                          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#updateCartModal{{ cart_item.id }}">
                              Обновить количество
                          </button>
                          <form method="post" action="{% url 'cart:delete_from_cart' cart_item.id %}" class="d-inline">
                              {% csrf_token %}
                              <button type="submit" class="btn btn-danger">Удалить</button>
                          </form>

                          <!-- Модальное окно для каждого товара -->
                          <div class="modal fade" id="updateCartModal{{ cart_item.id }}" tabindex="-1" role="dialog" aria-labelledby="updateCartModalLabel{{ cart_item.id }}" aria-hidden="true">
                              <div class="modal-dialog" role="document">
                                  <div class="modal-content">
                                      <div class="modal-header">
                                          <h5 class="modal-title">Update Cart Item: {{ cart_item.product.name }}</h5>
                                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                              <span aria-hidden="true">&times;</span>
                                          </button>
                                      </div>
                                      <form method="post" action="{% url 'cart:update_cart' cart_item.id %}">
                                          <div class="modal-body">
                                              {% csrf_token %}
                                              <input type="number" name="quantity" value="{{ cart_item.quantity }}" class="form-control">
                                          </div>
                                          <div class="modal-footer">
                                              <button type="submit" class="btn btn-primary">Обновить количество</button>
                                          </div>
                                      </form>
                                  </div>
                              </div>
                          </div>
                      {% endfor %}
                      <hr> <!-- Горизонтальная линия для разделения секций -->
                      <p class="text-right"><strong>Итого: {{ total_price }}</strong></p>
                      <div class="text-right">
                          <a href="{% url 'orders:create_order' %}" class="btn btn-success">Перейти к оформлению</a>
                      </div>
                  {% else %}
                      <p class="text-center">Ваша корзина пуста.</p>
                      <div class="text-center">
                          <a href="{% url 'product:product_list' %}" class="btn btn-secondary">Продолжить покупки</a>
                      </div>
                  {% endif %}
              </div>
          </div>
      </div>
  </div>
</div>
{% endblock %}

templates/cart/update_cart.html
{% extends 'base.html' %}

{% block content %}
{% extends 'base.html' %}

{% block content %}
  <h1>Update Cart Item</h1>
  <!-- Кнопка для открытия модального окна -->
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#updateCartModal">
    Обновить количество
  </button>

  <!-- Модальное окно -->
  <div class="modal fade" id="updateCartModal" tabindex="-1" role="dialog" aria-labelledby="updateCartModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="updateCartModalLabel">Update Cart Item</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form method="post">
          <div class="modal-body">
            {% csrf_token %}
            {{ form.as_p }}
          </div>
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Обновить количество</button>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
          </div>
        </form>
      </div>
    </div>
  </div>
{% endblock %}