accounts/urls.py
from django.urls import path
from accounts.views import login_view,logout_view,profile_view,create_profile,edit_profile
from .views import UserPasswordChangeView,RegisterView
from django.conf import settings
from django.conf.urls.static import static
app_name = 'accounts'
urlpatterns = [
    path('profile/', profile_view, name='profile'),
    path('profile/create', create_profile, name='create_profile'),
    path('profile/edit', edit_profile, name='edit_profile'),
    path('password_change/', UserPasswordChangeView.as_view(), name='change_password'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update_cart/<int:cart_item_id>/', views.update_cart, name='update_cart'),
    path('delete_from_cart/<int:cart_item_id>/', views.delete_from_cart, name='delete_from_cart'),
]

myecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter

from product.views import home_view, ProductDetailView, ProductReviewViewSet

router = DefaultRouter()
router.register(r'reviews', ProductReviewViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('accounts/', include('accounts.urls')),
    path('products/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    position = models.CharField(max_length=100, blank=True)
    phone = models.CharField(max_length=20, blank=True)
    avatar = models.ImageField(upload_to='avatars/', default='avatars/icon.jpg')

    def __str__(self):
        return self.user.username

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
# from cart.views import User
from .models import Profile
class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label=_('Имя пользователя'),
        required=True, 
        widget=forms.TextInput(attrs={'placeholder': _('Введите ваше имя пользователя')})
    )
    password = forms.CharField(
        label=_('Пароль'),
        widget=forms.PasswordInput(attrs={'placeholder': _('Введите ваш пароль')}),
        required=True  
    )
class MyUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        ]
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class':'form-control'}),
        }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = _('Имя пользователя')
        self.fields['first_name'].label = _('Имя')
        self.fields['last_name'].label = _('Фамилия')
        self.fields['email'].label = _('Электронная почта')
        self.fields['password1'].label = _('Пароль')
        self.fields['password2'].label = _('Подтверждение пароля')
        

class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(
        label='Новый пароль', 
        strip=False, 
        widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password_confirm = forms.CharField(
        label='Подтвердите пароль', 
        strip=False, 
        widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    old_password = forms.CharField(
        label='Старый пароль', 
        strip=False, 
        widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean_password_confirm(self):
        password = self.cleaned_data.get('password')
        password_confirm = self.cleaned_data.get('password_confirm')

        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли разные!')
        return password_confirm
    
    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')

        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неверный!')
        return old_password
    
    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data.get('password'))
        if commit:
            user.save()
        return user
    
    class Meta:
        model = get_user_model()
        fields = ['old_password', 'password', 'password_confirm']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['position', 'phone', 'avatar']
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['position'].label = _('Позиция')
        self.fields['phone'].label = _('Телефон')
        self.fields['avatar'].label = _('Аватарка')

class UserForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].label = _('Имя')
        self.fields['last_name'].label = _('Фамилия')
        self.fields['email'].label = _('Электронная почта')

accounts/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.views.generic import CreateView
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import MyUserCreationForm, PasswordChangeForm, ProfileForm, UserForm
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.models import User
from .models import Profile

def login_view(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            next = request.GET.get('next')
            if next:
                return redirect(next)
            return redirect('product:product_list')
        else:
            context['has_error'] = True
    return render(request=request, template_name='accounts/login.html', context=context)

def logout_view(request):
    logout(request)
    next = request.GET.get('next')
    if next:
        return redirect(next)
    return redirect('accounts:login')

def register_view(request):
    if request.method == 'POST':
        form = MyUserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('accounts:create_profile')
    else:
        form = MyUserCreationForm()
    return render(request, 'accounts/register.html', context={'form': form})

class RegisterView(CreateView):
    model = User
    template_name = 'accounts/register.html'
    form_class = MyUserCreationForm


    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next') or self.request.POST.get('next')
        if next_url:
            return next_url
        else:
            return reverse('accounts:profile')
@login_required
def create_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=getattr(request.user, 'profile', None))
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('accounts:profile')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=getattr(request.user, 'profile', None)) 

    return render(request, 'accounts/create_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })
@login_required
def edit_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return redirect('accounts:profile')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'accounts/edit_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })

@login_required
def profile_view(request):
    return render(request, 'accounts/profile.html', {
        'user': request.user
    })

class UserPasswordChangeView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    template_name = 'accounts/password_change.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_obj'

    def form_valid(self, form):
        user = form.save()
        update_session_auth_hash(self.request, user)
        return redirect(self.get_success_url())

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self) -> str:
        return reverse('accounts:profile')

templates/accounts/create_profile.html
{% extends "base.html" %}

{% block content %}
<h1>Create Profile</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <button type="submit" class="btn btn-primary">Create Profile</button>
</form>
{% endblock %}

templates/accounts/edit_profile.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
      <div class="col-md-6">
          <div class="card shadow">
              <div class="card-body">
                  <h1 class="text-center mb-4">Редактирования профиля</h1>
                  <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="w-100">
                    <strong>Имя:</strong>{{ user_form.first_name }}<br>
                    <p></p>
                    <strong>Фамилия:</strong> {{ user_form.last_name }}<br>
                  <p></p> 
                    <strong>Электронная почта:</strong> {{ user_form.email }}<br>
                    <p></p> 
                    {{ profile_form.as_p }}  
                    </div>
                    <button type="submit">Update Profile</button>
                  </form>
                </div>
              </div>
            </div>             
{% endblock %}

templates/accounts/login.html
 {% extends 'base.html' %}

 {% block content %}

 <div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow">
                <div class="card-body">
                    <h1 class="text-center mb-4">Вход</h1>
                <form action="{% url 'accounts:login' %}" method="POST" class="">
                 {% csrf_token %}
                 {% if has_error %}
                     <p>Имя пользователя или пароль указано неверно.</p>
                 {% endif %}
 
                 <div class="mb-3">
                     <label for="username" class="form-label">Имя пользователя</label>
                     <input type="text" name="username" id="username" class="form-control">
                 </div>
 
                 <div class="mb-3">
                     <label for="password" class="form-label">Пароль</label>
                     <input type="password" name="password" id="password" class="form-control">
                 </div>
 
                 <button type="submit" class="btn btn-primary">Войти</button>
             </form>
             <p>Если вы не зарегистрированы, <a href="{% url 'accounts:register' %}">пройдите регистрацию</a>.</p>
         </div>
     </div>
 </body>
 </html>
 {% endblock %}

templates/accounts/password_change.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow">
                <div class="card-body">
<div class="container">
    <h2>Изменить пароль</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Сменить пароль</button>
    </form>
</div>
</div>
</div>
</div>
</div>
</div>

{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow">
                <div class="card-body">
                    <div class="container profile-container">
                        <div class="profile-image">
                            <img src="{{ user.profile.avatar.url }}" alt="Profile image" class="rounded-circle">
                                </div>
                                <div class="profile-info">
                                <h2>{{ user.username }}</h2>
                                <p>Email: {{ user.email }}</p>
                                <p>Позиция: {{ user.profile.position }}</p>
                                <p>Телефон: {{ user.profile.phone }}</p>
                                <a href="{% url 'accounts:edit_profile' %}" class="btn btn-primary">Редактировать профиль</a>
                                <a href="{% url 'accounts:change_password' %}" class="btn btn-secondary">Изменить пароль</a>
                            </div>
</div></div></div></div>
{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow">
                <div class="card-body">
                    <h1 class="text-center mb-4">Регистрация</h1>
                        <form action="{% url 'accounts:register' %}?next={{ request.GET.next }}" method="POST"class="needs-validation" novalidate>
                         {% csrf_token %}
                        <div class="w-100">
                        {% for error in form.non_field_errors %}
                        <p class="alert alert-danger">{{ error }}</p>
                        {% endfor %}
                        {% for field in form %}
                        <div class="mb-3">
                        <label class="form-label" for="{{ field.id_for_label }}">{{ field.label}}</label>
                            {{ field }}
                            {% for error in field.errors %}
                <p class="text-danger">{{ error }}</p>
            {% endfor %}
        </div>
    {% endfor %}
</div>
<button type="submit" class="btn btn-primary mt-3">Регистрация</button>
</form>
</div>
</div>
</div>
</div>
</div>


{% endblock %}