accounts/urls.py
from django.urls import path
from accounts.views import login_view,logout_view,profile_view,create_profile,edit_profile
from .views import UserPasswordChangeView,RegisterView
from django.conf import settings
from django.conf.urls.static import static
app_name = 'accounts'
urlpatterns = [
    path('profile/', profile_view, name='profile'),
    path('profile/create', create_profile, name='create_profile'),
    path('profile/edit', edit_profile, name='edit_profile'),
    path('password_change/', UserPasswordChangeView.as_view(), name='change_password'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update_cart/<int:cart_item_id>/', views.update_cart, name='update_cart'),
    path('delete_from_cart/<int:cart_item_id>/', views.delete_from_cart, name='delete_from_cart'),
]

myecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter

from product.views import home_view, ProductDetailView, ProductReviewViewSet

router = DefaultRouter()
router.register(r'reviews', ProductReviewViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('accounts/', include('accounts.urls')),
    path('products/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from . import views
app_name = 'product'

urlpatterns = [
    path('', views.product_list_view, name='product_list'),
    path('detail/<int:pk>/', views.product_detail, name='product_detail'),
    path('detail/<int:pk>/submit_review/', views.product_review_submit, name='product_review_submit'),
    path('form',views.product_create_view,name='product_form'),
    path('category/skincare/', views.skincare_products, name='skincare_products'),
    path('category/makeup/', views.makeup_products, name='makeup_products'),
    path('category/haircare/', views.haircare_products, name='haircare_products'),
    path('out_of_stock/', views.out_of_stock, name='out_of_stock'),
]

product/models.py
from django.db import models
from orders.models import Order
class Brand(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Product(models.Model):
        name = models.CharField(max_length=255)
        description = models.TextField()
        price = models.DecimalField(max_digits=10, decimal_places=2)
        in_stock = models.BooleanField(default=True)
        category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
        brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, null=True, related_name='products')
        image = models.ImageField(upload_to='product/')
        quantity = models.PositiveIntegerField(default=0) 

def __str__(self):
        return self.name

class ProductReview(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='reviews')
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE ,null=True, related_name='reviews')
    is_approved = models.BooleanField(default=False) 

def __str__(self):
    order_status = f", Order status: {self.order.status}" if self.order else ""
    return f'{self.user.username} - {self.product.name} - Rating: {self.rating}{order_status}'

product/forms.py
from django import forms
from .models import Product, ProductReview

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'in_stock', 'category','brand', 'image','quantity']

    error_messages = {
        'name': {
            'required': 'Please enter a name for the product.',
            'max_length': 'The name of the product cannot be longer than 255 characters.',
        },
        'description': {
            'required': 'Please enter a description for the product.',
        },
        'price': {
            'required': 'Please enter a price for the product.',
            'invalid': 'Please enter a valid price for the product.',
        },
        'in_stock': {
            'required': 'Please indicate whether the product is in stock.',
        },
        'category': {
            'required': 'Please select a category for the product.',
        },
        'brand':{
            'required':'Please select a brand for the product.',
        },
        'image': {
            'required': 'Please upload an image for the product.',
            'invalid': 'Please upload a valid image file.',
            'max_length': 'Image file size must be less than 2 MB.',
        },
        'quantity': {
            'required': 'Pleace enter a quantity of a product',
        },
    }

    def clean_price(self):
        price = self.cleaned_data['price']
        if price < 0:
            raise forms.ValidationError('Price must be a positive number.')
        return price

    def clean_image(self):
        image = self.cleaned_data['image']
        if image.size > 2 * 1024 * 1024:
            raise forms.ValidationError('Image file size must be less than 2 MB.')
        return image
class ProductReviewForm(forms.ModelForm):
    class Meta:
        model = ProductReview
        fields = ('rating', 'comment')

    def clean(self):
        cleaned_data = super().clean()
        rating = cleaned_data.get('rating')
        comment = cleaned_data.get('comment')

        if not rating or not comment:
            self.add_error('rating', 'Rating is required.')
            self.add_error('comment', 'Comment is required.')

product/views.py
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models import Q
from django.urls import reverse
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from orders.models import OrderItem
from product.serializers import ProductSerializer,ProductReviewSerializer
from .models import  Product, ProductReview
from .forms import ProductForm, ProductReviewForm
from rest_framework import viewsets,generics
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework import viewsets
from .permissions import  IsOwnerOrReadOnly, IsAdminOrReadOnly, IsAuthenticatedOrReadOnly
from django.http import JsonResponse

from rest_framework import viewsets, status
def home_view(request):
    return render(request, 'home.html')

def product_list_view(request):
    query = request.GET.get('q', '')
    sort_by = request.GET.get('sort_by', '')
    page_request = request.GET.get('page', 1)

    products = Product.objects.all().order_by('id')
    if query:
        products = products.filter(Q(name__icontains=query) | Q(description__icontains=query))
    if sort_by == 'price-low-high':
        products = products.order_by('price')
    elif sort_by == 'price-high-low':
        products = products.order_by('-price')

    paginator = Paginator(products, 3)
    try:
        products = paginator.page(page_request)
    except PageNotAnInteger:
        return redirect('?page=1')
    except EmptyPage:
        return redirect(f'?page={paginator.num_pages}')

    context = {
        'products': products, 
        'object_list': products,  
        'query': query,
        'sort_by': sort_by
    }

    return render(request, 'product/list.html', context)

def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    reviews = ProductReview.objects.filter(product=product, is_approved=True)
    user_has_purchased = False
    new_review = None

    if request.user.is_authenticated:
        user_has_purchased = True

    review_form = ProductReviewForm()

    context = {
        'product': product,
        'reviews': reviews,
        'new_review': new_review,
        'review_form': review_form,
        'user_has_purchased': user_has_purchased
    }
    return render(request, 'product/detail.html', context)
def is_admin(user):
    return user.is_active and user.is_staff
@login_required
@user_passes_test(is_admin)
def product_create_view(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.user = request.user
            product.save()
            messages.success(request, 'Your product has been created.')
            return redirect(reverse('product:product_list'))
    else:
        form = ProductForm()

    context = {
        'form': form,
    }

    return render(request, 'product/form.html', context)

@login_required
@user_passes_test(is_admin)
def product_edit_view(request, pk):
    product = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            product = form.save()
            messages.success(request, 'Your product has been updated.')
            return redirect(reverse('product:product_detail', args=[product.pk]))
    else:
        form = ProductForm(instance=product)

    context = {
        'form': form,
    }

    return render(request, 'product/form.html', context)

@login_required
@user_passes_test(is_admin)
def product_delete_view(request, pk):
    product = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        product.delete()
        messages.success(request, 'Your product has been deleted.')
        return redirect(reverse('product:product_list'))

    context = {
        'product': product,
    }

    return render(request, 'products/product_confirm_delete.html', context)

def skincare_products(request):
    products = Product.objects.filter(category__name='Уход за лицом')

    query = request.GET.get('q')
    if query:
        products = products.filter(name__icontains=query)

    sort_by = request.GET.get('sort_by')
    if sort_by == 'price-low-high':
        products = products.order_by('price')
    elif sort_by == 'price-high-low':
        products = products.order_by('-price')


    paginator = Paginator(products, 3)  
    page_number = request.GET.get('page', 1)

    try:
        products_page = paginator.page(page_number)
    except PageNotAnInteger:
        # Если страница не является целым числом, доставить первую страницу
        products_page = paginator.page(1)
    except EmptyPage:
        # Если страница выходит за допустимый диапазон (например, 9999), доставить последнюю страницу
        products_page = paginator.page(paginator.num_pages)

    return render(request, 'category/skincare.html', {
        'products': products_page,  # передаем пагинированную страницу
        'query': query,
        'sort_by': sort_by
    })

def makeup_products(request):
    products = Product.objects.filter(category__name='Макияж')

    query = request.GET.get('q')
    if query:
        products = products.filter(name__icontains=query)

    sort_by = request.GET.get('sort_by')
    if sort_by == 'price-low-high':
        products = products.order_by('price')
    elif sort_by == 'price-high-low':
        products = products.order_by('-price')

    paginator = Paginator(products, 3)  
    page_number = request.GET.get('page', 1)

    try:
        products_page = paginator.page(page_number)
    except PageNotAnInteger:
        # Если страница не является целым числом, доставить первую страницу
        products_page = paginator.page(1)
    except EmptyPage:
        # Если страница выходит за допустимый диапазон (например, 9999), доставить последнюю страницу
        products_page = paginator.page(paginator.num_pages)

    return render(request, 'category/makeup.html', {
        'products': products_page,  # передаем пагинированную страницу
        'query': query,
        'sort_by': sort_by
    })

def haircare_products(request):
    products = Product.objects.filter(category__name='Уход за волосами')

    query = request.GET.get('q')
    if query:
        products = products.filter(name__icontains=query)

    sort_by = request.GET.get('sort_by')
    if sort_by == 'price-low-high':
        products = products.order_by('price')
    elif sort_by == 'price-high-low':
        products = products.order_by('-price')

    paginator = Paginator(products, 3)  
    page_number = request.GET.get('page', 1)

    try:
        products_page = paginator.page(page_number)
    except PageNotAnInteger:
        # Если страница не является целым числом, доставить первую страницу
        products_page = paginator.page(1)
    except EmptyPage:
        # Если страница выходит за допустимый диапазон (например, 9999), доставить последнюю страницу
        products_page = paginator.page(paginator.num_pages)

    return render(request, 'category/haircare.html', {
        'products': products_page,  # передаем пагинированную страницу
        'query': query,
        'sort_by': sort_by
    })
@login_required
@user_passes_test(is_admin)
def out_of_stock(request):
    products = Product.objects.filter(quantity=0)
    return render(request, 'product/out_of_stock.html', {'products': products})
class ProductDetailView(generics.RetrieveAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
class ProductReviewViewSet(viewsets.ModelViewSet):
    queryset = ProductReview.objects.all()
    serializer_class = ProductReviewSerializer
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly, IsAdminOrReadOnly]

    def perform_create(self, serializer):
        # Присвоение текущего пользователя в качестве автора отзыва
        serializer.save(user=self.request.user)

    def destroy(self, request, *args, **kwargs):
        instance = self.get_object()
        # Проверка прав пользователя перед удалением
        self.check_object_permissions(self.request, instance)
        self.perform_destroy(instance)
        return Response(status=status.HTTP_204_NO_CONTENT)
def product_review_submit(request, pk):
    if request.method == 'POST' and request.user.is_authenticated:
        review_form = ProductReviewForm(request.POST)
        if review_form.is_valid():
            review = review_form.save(commit=False)
            review.user = request.user
            review.product = get_object_or_404(Product, pk=pk)
            review.save()
            return JsonResponse({'success': True})
        else:
            return JsonResponse({'success': False, 'errors': review_form.errors}, status=400)
    else:
        return JsonResponse({'success': False, 'errors': 'Authentication required'}, status=401)

templates/product/detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5 mb-5">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ product.image.url }}" alt="{{ product.name }}" class="img-fluid">
        </div>

  
        <div class="col-md-6">
            <h2 class="text-uppercase">{{ product.name }}</h2>
            <p class="description">Описание продукта:{{ product.description }}</p>
            <p class="price">Цена: {{ product.price }} тг</p>
            <p class="in-stock">В наличии: {% if product.in_stock %}Да{% else %}Нет{% endif %}</p>
            <p class="category">Категория: {{ product.category.name }}</p>
            <p class="brand">Бренд: {{ product.brand.name }}</p>


            {% if product.in_stock %}
            <form id="add-to-cart-form-{{ product.pk }}" method="post" action="{% url 'cart:add_to_cart' product.pk %}">
              {% csrf_token %}
              <div class="form-group">
                  <label for="quantity">Количество:</label>
                  <input type="number" name="quantity" id="quantity-{{ product.pk }}" class="form-control" value="1" min="1">
              </div>
              <button type="submit" class="add-to-cart-btn" data-product-id="{{ product.pk }}">Добавить в корзину</button>
          </form>
          
            {% endif %}
          </div>
        </div>
    
          
        <div class="reviews mt-4">
            <h3>Отзывы:</h3>
            {% for review in reviews %}
            <div class="review">
                <strong>{{ review.user.username }}</strong> - {{ review.rating }} звезд
                <p>{{ review.comment }}</p>
                <small>Reviewed on {{ review.created_at }}</small>
            </div>
            {% empty %}
            <p>Отзывов пока нет.</p>
            {% endfor %}
        
      {% if user.is_authenticated %}


            <div class="add-review mt-4">
                <h4>Оставьте отзыв:</h4>
                <form id="reviewForm">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="rating">Рейтинг:</label>
                        <select name="rating" id="rating" class="form-control">
                            <option value="1">1 звезда</option>
                            <option value="2">2 звезды</option>
                            <option value="3">3 звезды</option>
                            <option value="4">4 звезды</option>
                            <option value="5">5 звезд</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="comment">Комментарий:</label>
                        <textarea name="comment" id="comment" class="form-control" rows="4"></textarea>
                    </div>
                    <button type="button" id="submitReview" class="btn btn-primary" data-productpk="{{ product.pk }}">Отправить отзыв</button>

                </form>
            </div>
            
          {% else %}
      <p>Вы должны <a href="{% url 'accounts:login' %}">войти</a>, чтобы оставить отзыв.</p>
      {% endif %}
    </div>


  {% endblock %}

templates/product/form.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
      <div class="col-md-6">
          <div class="card shadow">
              <div class="card-body">
                            <h1>Добавить товар</h1>
                          <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                              <label for="id_name">Название:</label>
                              {{ form.name }}
                            </div>
                            <div class="form-group">
                              <label for="id_description">Описание:</label>
                              {{ form.description }}
                            </div>
                            <div class="form-group">
                              <label for="id_price">Цена:</label>
                              {{ form.price }}
                            </div>
                            <div class="form-group">
                              <label for="id_in_stock">В продаже:</label>
                              {{ form.in_stock }}
                            </div>
                            <div class="form-group">
                              <label for="id_category">Категория:</label>
                              {{ form.category }}
                            </div>
                            <div class="form-group">
                              <label for="id_brand">Бренд:</label>
                              {{ form.brand }}
                            </div>
                            <div class="form-group">
                              <label for="id_image">Фото:</label>
                              {{ form.image }}
                            </div>
                            <div class="form-group">
                              <label for="id_quantity">Количество:</label>
                              {{ form.quantity }}
                            </div>
                            <button type="submit" class="btn btn-primary mt-3">Добавить Продукт</button>
                          </form>
                        </div>
                    </div>
                 </div>
              </div>
          </div>
{% endblock %}

templates/product/list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h1 class="text-center my-4">Каталог товаров</h1>

  <!-- Форма поиска -->
  <form method="get" class="mb-4">
    <div class="input-group">
      <input type="text" name="q" class="form-control" placeholder="Поиск товаров" value="{{ request.GET.q }}">
      <div class="input-group-append">
        <button type="submit" class="btn btn-outline-secondary">Поиск</button>
      </div>
    </div>
  </form>

  <!-- Кнопки сортировки -->
  <div class="d-flex justify-content-end mb-3">
    <a href="?sort_by=price-low-high" class="btn btn-light">Цена по возрастанию</a>
    <a href="?sort_by=price-high-low" class="btn btn-light">Цена по убыванию</a>
  </div>

  <!-- Список товаров -->
  <div class="row">
    {% for product in object_list %}
    <div class="col-md-4 mb-4">
      <div class="card">
        <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
        <div class="card-body">
          <h5 class="card-title">{{ product.name }}</h5>
          <p class="card-text">Цена: {{ product.price }} тг.</p>
          <a href="{% url 'product:product_detail' product.pk %}" class="btn btn-primary">Детали</a>
        </div>
      </div>
    </div>
    {% empty %}
    <div class="col-12">
      <p>Товары не найдены.</p>
    </div>
    {% endfor %}
  </div>
  {% include 'partials/pagination.html' %}


{% endblock %}

templates/product/moderation_page.html
{% extends 'base.html' %}

{% block content %}
<h1>Модерация отзывов</h1>
<table>
  <tr>
    <th>Продукт</th>
    <th>Отзыв</th>
    <th>Действия</th>
  </tr>
  {% for review in reviews %}
  <tr>
    <td>{{ review.product.name }}</td>
    <td>{{ review.comment }}</td>
    <td>
      <a href="{% url 'product:approve_review' review.id %}">Одобрить</a>
      <a href="{% url 'product:reject_review' review.id %}">Отклонить</a>
    </td>
  </tr>
  {% empty %}
  <tr>
    <td colspan="3">Нет отзывов, ожидающих модерации.</td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

templates/product/out_of_stock.html
{% extends 'base.html' %}

{% block content %}
  <h1>Out of Stock Products</h1>
  <ul>
    {% for product in products %}
      <li>{{ product.name }}</li>
    {% empty %}
      <li>No out of stock products found.</li>
    {% endfor %}
  </ul>
{% endblock %}