accounts/urls.py
from django.urls import path
from accounts.views import login_view,logout_view,profile_view,create_profile,edit_profile
from .views import UserPasswordChangeView,RegisterView
from django.conf import settings
from django.conf.urls.static import static
app_name = 'accounts'
urlpatterns = [
    path('profile/', profile_view, name='profile'),
    path('profile/create', create_profile, name='create_profile'),
    path('profile/edit', edit_profile, name='edit_profile'),
    path('password_change/', UserPasswordChangeView.as_view(), name='change_password'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update_cart/<int:cart_item_id>/', views.update_cart, name='update_cart'),
    path('delete_from_cart/<int:cart_item_id>/', views.delete_from_cart, name='delete_from_cart'),
]

myecommerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from rest_framework.routers import DefaultRouter

from product.views import home_view, ProductDetailView, ProductReviewViewSet

router = DefaultRouter()
router.register(r'reviews', ProductReviewViewSet)

urlpatterns = [
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('accounts/', include('accounts.urls')),
    path('products/', include('product.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
path('create/', views.create_order, name='create_order'),
path('confirm/<int:order_id>/', views.confirm_order, name='confirm_order'),
path('awaiting_payment/<int:order_id>/', views.awaiting_payment, name='awaiting_payment'),
path('pay/<int:order_id>/', views.pay_order, name='pay_order'),
path('<int:order_id>/', views.order_detail, name='order_detail'),
path('<int:order_id>/cancel/', views.cancel_order, name='cancel_order'),
path('', views.order_history, name='order_history'),
path('thank_you/<int:order_id>',views.thank_you,name='thank_you'),
]

product/urls.py
from django.urls import path
from . import views
app_name = 'product'

urlpatterns = [
    path('', views.product_list_view, name='product_list'),
    path('detail/<int:pk>/', views.product_detail, name='product_detail'),
    path('detail/<int:pk>/submit_review/', views.product_review_submit, name='product_review_submit'),
    path('form',views.product_create_view,name='product_form'),
    path('category/skincare/', views.skincare_products, name='skincare_products'),
    path('category/makeup/', views.makeup_products, name='makeup_products'),
    path('category/haircare/', views.haircare_products, name='haircare_products'),
    path('out_of_stock/', views.out_of_stock, name='out_of_stock'),
]

templates/base.html
<!DOCTYPE html>
<html lang="ru">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Korean Beauty</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    {% block extra_css %}{% endblock %}
</head>
<body><header>
    <div class="header-container">
        <div class="logo">
            <a href="{% url 'home' %}">
                <img src="{% static 'images/korean_beauty1.png' %}" alt="Korean Beauty Logo">
            </a>
        </div>
        <nav class="main-nav">
            <ul class="navbar-nav ml-auto"> 
                <div class="shopping-cart">
                    <a href="{% url 'cart:cart_detail' %}" class="cart-link">
                        <i class="fas fa-shopping-bag"></i> 
                        <span class="badge badge-pill badge-danger">{{ request.cart.total_items }}</span>
                    </a>
                </div>
                              
                {% if request.user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ request.user.get_full_name|default:request.user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'accounts:profile' %}">Профиль</a>
                            {% if request.user.is_staff %}
                            <a class="dropdown-item" href="{% url 'product:product_form' %}">Добавить товар</a>
                            {% endif %}
                            <a class="dropdown-item" href="{% url 'accounts:change_password' %}">Изменить пароль</a>
                            <a class="dropdown-item" href="{% url 'orders:order_history' %}">Заказы</a>
                            <a class="dropdown-item" href="{% url 'accounts:logout' %}">Выйти</a>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <button id="loginButton" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#loginModal">
                            Войти
                        </button>                      
                    </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>
</header>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

    <main>
        {% block content %}

        {% endblock %}
    </main>

    <footer>
        <div class="footer-container">
            <p>&copy; 2024 Korean Beauty</p>
        </div>
    </footer>

    <div id="loginModal" class="modal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="loginModalLabel">Вход</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post" action="{% url 'accounts:login' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Имя пользователя:</label>
                            <input type="text" class="form-control" name="username" id="username" required>
                        </div>
                        <div class="form-group">
                            <label for="password">Пароль:</label>
                            <input type="password" class="form-control" name="password" id="password" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Войти</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <p>Если вы не зарегистрированы, <a href="{% url 'accounts:register' %}">пройдите регистрацию</a>.</p>
                </div>
            </div>
        </div>
    </div>
        {% block extra_js %}{% endblock %}

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'js/index.js' %}"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
{% load static %} 
<div class="welcome-container">
  <h1>Добро пожаловать на сайт корейской косметики</h1>
  <p>Выберите нужную категорию продукта:</p>
</div>

  <main class="container">
    <div class="row text-center">
        <div class="col-md-3">
            <a href="{% url 'product:skincare_products' %}"> 
                <img src="{% static 'images/skincare.png' %}" alt="Уход за кожей" class="img-fluid">
            </a>
        </div>
        <div class="col-md-3">
            <a href="{% url 'product:makeup_products' %}">
                <img src="{% static 'images/makeup.png' %}" alt="Макияж" class="img-fluid">
            </a>
          </div>
        <div class="col-md-3">
          <a href="{% url 'product:haircare_products' %}">
              <img src="{% static 'images/hair_care.jpg' %}" alt="Уход за волосами" class="img-fluid">
          </a>
        </div>
          <div class="col-md-3">
              <a href="{% url 'product:product_list' %}">
                  <img src="{% static 'images/all_product.png' %}" alt="Все продукты" class="img-fluid">
              </a>
            </div>
    </div> 
</main>
{% endblock %}